name: CloudFormation Guard Pull Request

on:
  pull_request:

jobs:
  guard:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    name: CloudFormation Guard Pull Request
    steps:
      - name: CloudFormation Guard Validate
        uses: aws-cloudformation/cloudformation-guard@action-v0.0.2
        with:
          rules: 'resources/validate/rules'
          data: 'resources/validate/data'
